version: "3.7"
services:
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    ports:
      - 4000:80
    environment:
      PMA_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:latest"
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: public
      MYSQL_ROOT_PASSWORD: admin
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./data/mysql:/docker-entrypoint-initdb.d
  pgadmin:
    image: "dpage/pgadmin4:latest"
    ports:
      - 4001:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes: 
      - ./data/pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgresdb
  postgresdb:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bar
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
      - ./output:/output
  pgloader:
    image: "dimitri/pgloader:latest"
